# Generated by Django 4.2.20 on 2025-05-27 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_friendship_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpreference',
            name='preferred_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
