# Generated by Django 4.2.20 on 2025-06-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_enable_rls_policies'),
        ('users', '0005_userpreference_preferred_categories'),
    ]

    operations = [
    ]
