# Generated by Django 4.2.20 on 2025-06-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_chat', '0002_enable_rls_policies'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'chat_session'], name='ai_chat_cha_user_id_34b82d_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'created_at'], name='ai_chat_cha_user_id_84a4ee_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'chat_session', 'created_at'], name='ai_chat_cha_user_id_f86e61_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['chat_session', '-created_at'], name='ai_chat_cha_chat_se_c0ee06_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['title'], name='ai_chat_cha_title_f0817f_idx'),
        ),
    ]
