# Generated by Django 4.2.20 on 2025-06-01 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_alter_event_image_path_alter_event_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='category',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['category'], name='events_categor_a7129c_idx'),
        ),
    ]
