# Generated by Django 4.2.20 on 2025-06-18 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_enable_rls_policies'),
        ('events', '0004_event_category_event_event_address_and_more'),
    ]

    operations = [
    ]
